# common production services

version: '3.1'

services:
  # https://hub.docker.com/_/zookeeper
  zookeeper:
    image: zookeeper:3.6.3
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      # The length of a single tick, which is the basic time unit used by
      # ZooKeeper, as measured in milliseconds. It is used to regulate
      # heartbeats, and timeouts. For example, the minimum session timeout will
      # be two ticks
      ZOO_TICK_TIME: 2000
    restart: unless-stopped

  # alternatively: https://hub.docker.com/r/bitnami/kafka
  broker:
    image: confluentinc/cp-kafka:6.2.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

  kafka-connect:
    image: yitaekhwang/cp-kafka-connect-postgres:6.1.0
    hostname: connect
    container_name: connect
    depends_on:
      - broker
      - zookeeper
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

  database:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg11
    env_file:
      - init.d/env.timescaledb
    volumes:
      - timescaledb:/var/lib/postgresql/data
      - ./init.d:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.7
    env_file:
      - init.d/env.grafana
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  timescaledb:
  grafana:
